### ISSUE TITLE
コード5.7.5 PlannerSample.pyのプラグインについて

### ISSUE THREAD

**Issue by BanquetKuma** [AvanadeJapanPublishingQuery/AzureOpenAIServicePracticalGuide-book#4]
書籍中記載）SummarizeSkill　⇒　レポジトリのフォルダ名）SummarizePlugin
書籍中記載）WriterSkill ⇒　レポジトリのフォルダ名）WriterPlugin
ダウンロードしたレポジトリの内容から上記表記になるとと思います。

また、上記に記載にフォルダ名を変更し PlannerSample.pyを実行したところ、以下のエラーが発生しました。
解決策教示いただけますと幸いです。

`Traceback (most recent call last):
  File "C:\~Azure OpenAI Service実践ガイドハンズオン\Chapter-05\5.7\PlannerSample.py", line 49, in <module>
    asyncio.run(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2288.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\~Azure OpenAI Service実践ガイドハンズオン\Chapter-05\5.7\PlannerSample.py", line 32, in main
    summarize_plugin = kernel.import_semantic_skill_from_directory(plugin_directory, "SummarizePlugin")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\~\.venv\Lib\site-packages\semantic_kernel\kernel.py", line 867, in import_semantic_skill_from_directory
    config = config.from_json(config_file.read())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\~\.venv\Lib\site-packages\semantic_kernel\semantic_functions\prompt_template_config.py", line 122, in from_json
    return PromptTemplateConfig.from_dict(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\~\.venv\Lib\site-packages\semantic_kernel\semantic_functions\prompt_template_config.py", line 57, in from_dict
    completion_dict = data["completion"]
                      ~~~~^^^^^^^^^^^^^^

**KeyError: 'completion'`**

**Comment by AvanadeJapanPublishingQuery** [comment]
ご質問ありがとうございます。
調査に時間がかかりましたことをお詫び申し上げます。
おかげさまで問題の原因を特定することができました。

**原因**
書籍執筆時に存在していたフォルダーがGitHub上から消えており、かつ新しく作成されているPlugin内にあるconfigの記載が直近１か月以内に変わっておりました。そのため、書籍に記載しているSemantic Kernelのバージョンで新しいPluginを実行すると同じようなエラーが発生します。
GitHub上のリポジトリが更新されることによる影響を十分に考慮できていなかったことが、本件の根本的な原因でした。

**対策**
元々の Microsoft / semantic-kernel のリポジトリで Plugin の過去の履歴を調査し対応できるURLを探しました。
変更になり、存在しなくなったリポジトリ
https://github.com/microsoft/semantic-kernel/tree/main/samples/skills
最新のリポジトリ
https://github.com/microsoft/semantic-kernel/tree/main/samples/plugins
こちらを利用すると、ご指摘のエラーになります
過去の変更履歴から、こちらのリポジトリであれば動作可能となります。
https://github.com/microsoft/semantic-kernel/tree/python-0.3.15.dev/samples/skills

**修正**
***書籍の修正***
(書籍の通り改行すると、URLがくずれてしまうため、こちらのURLでは書籍に合わせた改行表現はしておりません。)
修正前
使用するプラグインについては、マイクロソフトのGitHub「[https://github.com/microsoft/semantic-kernel/tree/main/samples/skills](https://github.com/microsoft/semantic-kernel/tree/main/samples/skills)」からダウンロードした後、保存先を以下のコードのplugin_directoryで指定してください。
修正後
使用するプラグインについては、マイクロソフトのGitHub「[https://github.com/microsoft/semantic-kernel/tree/python-0.3.15.dev/samples/skills](https://github.com/microsoft/semantic-kernel/tree/python-0.3.15.dev/samples/skills)」からダウンロードした後、保存先を以下のコードのplugin_directoryで指定してください。

加えて、下のサンプルコードの部分も修正となります。
サンプルコードの修正は、以下の「リポジトリの修正」と同じとなります。
（ソースコードの部分のみ。コメント部分は元々書籍と異なります。）

***リポジトリの修正***

変更前  24行目、25行目
    #https://github.com/microsoft/semantic-kernel/tree/main/samples/pluginsからダウンロードしてローカルでインポート
    plugin_directory = "../../samples/plugin/"
変更後  24行目、25行目
    #https://github.com/microsoft/semantic-kernel/tree/python-0.3.15.dev/samples/skillsからダウンロードしてローカルでインポート
    plugin_directory = "../../samples/skills/"
    
修正後のリポジトリは以下となります。
https://github.com/AvanadeJapanPublishingQuery/AzureOpenAIServicePracticalGuide-book/tree/main/Chapter-05-Azure-OpenAI-Tools-and-Techniques/Section-07-Semantic-Kernel/python

**書籍の修正**
第3刷が出た際には、この問題を修正した内容を反映させます。
本リポジトリでは、書籍の修正履歴を追加して対応致します。

**Comment by BanquetKuma** [comment]
回答ありがとうございました。
提供いただいた方法で再トライしたところ、実行できました。

しかし、添付画像の様に回答が1行しか出力されません。
原因として考えられることがあれば、教えていただけますと幸いです。

![スクリーンショット 2024-03-06 000925](https://github.com/AvanadeJapanPublishingQuery/AzureOpenAIServicePracticalGuide-book/assets/45278831/4c44cc2c-42b9-4a84-95ec-0049ea861976)
